### PR TITLE
Fixes dependency versions for base64 and result

### LINKED ISSUE #255: Issue with result dependency version
I get errors when trying to build with `result` pinned to version 1.4 (1.5 is the most recent version):

```
$ opam switch create . --empty
$ opam pin add result 1.4
$ opam install . --deps-only
$ dune build .
File "opium/src/cookie.ml", line 298, characters 7-23:
298 |     |> Result.to_option
             ^^^^^^^^^^^^^^^^
Error: Unbound value Result.to_option
```

### PR DESCRIPTION
**Pull request by roddyyaga**
Fixes #255 and #256

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -1,7 +1,7 @@
 Opium
 =====
 
-The current master branch is a WIP port to httpaf. If you are looking for the last version published to opam (that was using Cohttp), please take a look at https://github.com/rgrinberg/opium/tree/0.18.0
+Since version 0.19.0, Opium uses httpaf. The last version that used Cohttp can be found at https://github.com/rgrinberg/opium/tree/0.18.0
```
Comment (anuragsoni) [inline README.md:4]: These changes should be made to `README.cpp.md` otherwise they'll get over-written when that file gets promoted to `README.md`
