### ISSUE TITLE
Issue with result dependency version

### ISSUE THREAD

**Issue by roddyyaga** [rgrinberg/opium#255]
I get errors when trying to build with `result` pinned to version 1.4 (1.5 is the most recent version):

```
$ opam switch create . --empty
$ opam pin add result 1.4
$ opam install . --deps-only
$ dune build .
File "opium/src/cookie.ml", line 298, characters 7-23:
298 |     |> Result.to_option
             ^^^^^^^^^^^^^^^^
Error: Unbound value Result.to_option
```

**Comment by rgrinberg** [comment]
Indeed. Would you mind sending a PR?
